include:
  - remote: 'https://gitlab.com/pod_security/shared-ci/-/raw/main/security.yml'

image: 'registry.gitlab.com/shardus/dev-container'

before_script:
  - node -v

stages:
  - build
  - appsec

build-job:
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - echo "Compiling the code..."
    - npm install
    - npm run test
    - npm run compile
    - echo "Compile complete."

lint-checker-job:
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - echo "Running ESlint..."
    - npm install @typescript-eslint/eslint-plugin@5.48.0 --save-dev
    - npm run lint
    - echo "Running ESlint complete."

format-checker-job:
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - echo "Running Prettier..."
    - npm install prettier --save-dev
    - npm run format-check
    - echo "Running Prettier complete."
